# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

# temp comment
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - deploy:
          filters:
            branches:
              only: master
          command: ${DOCKER_HUB_TRIGGER}

      # - run: echo ${docker_hub_trigger}

# # The deployment section should be excluded until
# # it is explicitly included in module 5

# #deployment:
# #  dockerhub:
# #    branch: master
# #    commands:
# #      - $DOCKER_HUB_TRIGGER

# test:
#   override:    
#     - mocha

# The expected curl:  curl -H "Content-Type:application/json" --data '{"build":true}' -X POST https://cloud.docker.com/api/build/v1/source/3726ce78-f8d9-432b-a478-903258a4143e/trigger/fe249f31-28de-4a7b-9375-61a5b0a06bc9/call/